name: Build and Deploy Service 

on: 
  push: 
    branches: 
      - main

env: 
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  build-deploy: 
    runs-on: ubuntu-latest
    
    env: 
      APP_NAME: ${{ vars.APP_NAME }}
      APP_PORT : ${{ vars.APP_PORT }}
      DOCKER_IMAGE:  ${{ vars.DOCKER_IMAGE }}
      GITOPS_REPO: ${{ vars.GITOPS_REPO }}

    
    steps: 
    - name: Checkout source code
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        IMAGE=${DOCKER_IMAGE}:${GITHUB_SHA}
        docker build -t $IMAGE .
        docker push $IMAGE
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV
    
    - name: Checkout GitOps repo 
      uses: actions/checkout@v4
      with: 
        repository: ${{ env.GITOPS_REPO }}
        token: ${{ secrets.GITHUB_TOKEN }}
        path: gitops

    - name: Scaffold workload if missing
      run: |
        BASE=gitops/workloads/services/${APP_NAME}
        if [ ! -d "$BASE" ]; then
          mkdir -p $BASE
          cp -r gitops/templates/service/* "$BASE"/
          sed -i "s#__NAME__#${APP_NAME}#g" "$BASE"/*.yaml
          sed -i "s#__PORT__#${APP_PORT}#g" "$BASE"/*.yaml
        fi

    - name: Update image with Kustomize
      run: |
        cd gitops/workloads/services/${APP_NAME}
        kustomize edit set image placeholder=${IMAGE}
    
    - name: Commit and push to GitOps repo 
      run: |
        cd gitops
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        
        # Check if there are any changes to commit
        if ! git diff --quiet; then
          git add .
          git commit -m "Deploy ${APP_NAME} image ${IMAGE}"
          git pull origin main --rebase # Pull latest changes before pushing
          git push origin main
        else
          echo "No changes to commit to GitOps repository."
        fi